<?php

/**
 * @file
 * Provides integration with LiveStats.
 */

/**
 * Form builder for the LiveStats settings.
 */
function livestats_admin_form() {
  $form = array();

  $form['livestats_acctcode'] = array(
    '#type' => 'textfield',
    '#title' => t('Your site account code:'),
    '#default_value' => variable_get('livestats_acctcode', 'GSN-000000-X'),
    '#size' => 14,
    '#maxlength' => 13,
    '#description' => t('This is your site\'s account code from GoSquared\'s LiveStats service. If you do not have an account please go to <a href="http://www.gosquared.com/plans" target="_blank">http://www.gosquared.com/plans</a> to get one!'),
    '#required' => TRUE,
  );

  $form['livestats_trackadmin'] = array(
    '#type' => 'radios',
    '#title' => t('Track admin pages:'),
    '#default_value' => variable_get('livestats_trackadmin', 0),
    '#options' => array(t('Yes'), t('No')),
    '#description' => t('This option allows you choose whether you want LiveStats to track your admin pages.'),
    '#required' => TRUE,
  );

  $form['livestats_trackusers'] = array(
    '#type' => 'radios',
    '#title' => t('Display users as:'),
    '#default_value' => variable_get('livestats_trackusers', 2),
    '#options' => array(t('Off'), t('User ID'), t('Username')),
    '#description' => t('This sets whether or not the visitor ID\'s in LiveStats are replaced by the logged in user\'s details. Choose "Off" to use the deafult LiveStats ID, choose "User ID" to use the user\'s ID from Drupal and choose "Username" to use the user\'s username from Drupal.'),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

/**
 * Form validation handler for livestats_admin_form().
 */
function livestats_admin_form_validate($form, &$form_state) {
  $acctcode = $form_state['values']['livestats_acctcode'];
  if (!preg_match('/GSN-[0-9]{6,7}-[A-Z]{1}/', $acctcode)) {
    form_set_error('livestats_acctcode', t('The code you have entered is in an incorrect format. Please enter the code in this format: GSN-000000-X. If you do not have an account code then please go to <a href="http://www.gosquared.com/plans" target="_blank">http://www.gosquared.com/plans</a> to get one.'));
  }
}

/**
 * Implements hook_menu().
 */
function livestats_menu() {
  $items = array();

  $items['admin/settings/livestats'] = array(
    'title' => 'LiveStats',
    'description' => 'Use this page to configure your LiveStats module settings with your account code.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('livestats_admin_form'),
    'access arguments' => array('administer modules'),
  );

  return $items;
}

/**
 * Generates the JavaScript to be inserted.
 */
function livestats_set_js() {
  // Get the settings.
  $acct = variable_get('livestats_acctcode', 'GSN-000000-X');
  $track_users = variable_get('livestats_trackusers', 2);
  $track_admin = variable_get('livestats_trackadmin', 0);

  // Check they have entered their tracking code.
  if ($acct !='' && $acct != 'GSN-000000-X' && preg_match('/GSN-[0-9]{6,7}-[A-Z]{1}/', $acct)) {

    // Account code is valid so add it to the settings.
    drupal_add_js(array('livestats' => array('acct' => $acct)), 'setting');

    // Check if we are not tracking admin pages and if this is an admin page then return.
    if ($track_admin == 1) {
      if (arg(0) == 'admin') {
        return;
      }
    }

    // If tracking names, get the relevant information.
    $has_user_info = FALSE;
    if ($track_users != 0) {
      // Get current user.
      global $user;
      // Check if current user is not a guest.
      if ($user->uid) {
        $livestats_user = '';
        switch ($track_users) {
          case 1:
            $livestats_user = $user->uid;
            break;

          case 2:
            $livestats_user = $user->name;
            break;

          default:
            $livestats_user = FALSE;
            break;
        }
      $has_user_info = TRUE;
      }
    }

    // Now create the relevant JS.
    // Set the initial JS.
    $js = '
        var GoSquared={};
        GoSquared.acct = Drupal.settings.livestats.acct;
        ';
        if ($has_user_info) {
            // Now add that user string to the settings for the javascript to use.
            drupal_add_js(array('livestats' => array('user' => $livestats_user)), 'setting');
            // And add the relevant line to the javascript to be returned.
            $js .= 'GoSquared.VisitorName = Drupal.settings.livestats.user;';
        }
        $js .= '(function(w){
            function gs(){
              w._gstc_lt=+(new Date); var d=document;
              var g = d.createElement("script"); g.type = "text/javascript"; g.async = true; g.src = "//d1l6p2sc9645hc.cloudfront.net/tracker.js";
              var s = d.getElementsByTagName("script")[0]; s.parentNode.insertBefore(g, s);
            }
            w.addEventListener?w.addEventListener("load",gs,false):w.attachEvent("onload",gs);
          })(window);';
    // And now add to the body tag using return.
    return $js;
  }
  else {
    return;
  }
}

/**
 * Implements hook_init().
 */
function livestats_init() {
  if ($js = livestats_set_js()) {
    drupal_add_js($js, 'inline', 'footer');
  }
}
